import { ActivityType, Assets, getTimestampsFromMedia } from 'premid'

const presence = new Presence({
  clientId: '1491476633188569230',
})

enum ActivityAssets {
  Logo = 'https://nakios.website/premid/icon.png',
}

/**
 * Nakios is a single page app: its markup is generated by Tailwind, and its
 * player is an overlay that never changes the URL. Scraping it would be
 * brittle, so the site publishes what it currently shows through
 * `data-premid-*` attributes on `<html>`.
 *
 * Page namespace:   page, title, subtitle, genre, image, id, media
 * Player namespace: watching, watch-media, watch-title, watch-image,
 *                   watch-season, watch-episode, watch-episode-title
 */
function pageData(key: string): string | null {
  return document.documentElement.getAttribute(`data-premid-${key}`)
}

/** Covers are sometimes served as site-relative paths (franchise logos). */
function absoluteUrl(path: string | null): string | null {
  if (!path)
    return null
  try {
    return new URL(path, document.location.origin).href
  }
  catch {
    return null
  }
}

function join(...parts: (string | null | undefined)[]): string {
  return parts.filter(Boolean).join(' · ')
}

/**
 * Canonical URL of a page, built from its id rather than the current location:
 * whoever clicks the button on Discord lands on that exact title, with no
 * query string picked up along the way.
 */
function contentUrl(kind: string, id: string | null): string | null {
  return id ? `${document.location.origin}/${kind}/${id}` : null
}

const SETTINGS_TABS: Record<string, string> = {
  apercu: 'Vue d\'ensemble',
  apparence: 'Apparence',
  profils: 'Profils',
  historique: 'Historique',
  commentaires: 'Commentaires',
  compte: 'Mon compte',
  securite: 'Sécurité',
}

/** Routes with nothing dynamic to read, so no page ever shows a bare logo. */
const STATIC_PAGES: Record<string, { details: string, state: string }> = {
  '': { details: 'Page d\'accueil', state: 'Parcourt les nouveautés' },
  'franchises': { details: 'Franchises', state: 'Choisit un univers' },
  'watchlist': { details: 'Ma liste', state: 'Retrouve ses titres mis de côté' },
  'payment': { details: 'Nakios Premium', state: 'Regarde les offres' },
  'profiles': { details: 'Profils', state: 'Choisit un profil' },
  'pair': { details: 'Appairage', state: 'Connecte un appareil' },
  'dmca': { details: 'DMCA', state: 'Lit les mentions légales' },
  'admin': { details: 'Administration', state: 'Gère la plateforme' },
}

let browsingTimestamp = Math.floor(Date.now() / 1000)
let wasWatching = false

presence.on('UpdateData', async () => {
  const [privacy, showTimestamps, showCovers, showButtons] = await Promise.all([
    presence.getSetting<boolean>('privacy'),
    presence.getSetting<boolean>('timestamps'),
    presence.getSetting<boolean>('covers'),
    presence.getSetting<boolean>('buttons'),
  ])

  const { pathname, href } = document.location
  const [, section = '', slug = ''] = pathname.split('/')

  const video = document.querySelector<HTMLVideoElement>('video')
  const isWatching
    = pageData('watching') === '1'
      && !!video
      && video.readyState > 0
      && Number.isFinite(video.duration)

  // The elapsed timer restarts when leaving the player, otherwise Discord
  // would keep counting from the moment the tab was opened.
  if (wasWatching && !isWatching)
    browsingTimestamp = Math.floor(Date.now() / 1000)
  wasWatching = isWatching

  const presenceData: PresenceData = {
    type: ActivityType.Watching,
    largeImageKey: ActivityAssets.Logo,
    largeImageText: 'Nakios',
    startTimestamp: browsingTimestamp,
  }

  if (privacy) {
    presenceData.details = isWatching ? 'Regarde un contenu' : 'Navigue sur Nakios'
    presence.setActivity(presenceData)
    return
  }

  if (isWatching && video) {
    const isSeries = pageData('watch-media') === 'tv'
    const cover = absoluteUrl(pageData('watch-image'))

    presenceData.details = pageData('watch-title') ?? 'Contenu Nakios'
    presenceData.state = isSeries
      ? join(
          `S${pageData('watch-season') ?? '?'}E${pageData('watch-episode') ?? '?'}`,
          pageData('watch-episode-title'),
        )
      : join('Film', pageData('subtitle'))

    if (showCovers && cover)
      presenceData.largeImageKey = cover

    if (video.paused) {
      presenceData.smallImageKey = Assets.Pause
      presenceData.smallImageText = 'En pause'
      delete presenceData.startTimestamp
    }
    else {
      presenceData.smallImageKey = Assets.Play
      presenceData.smallImageText = 'Lecture'
      if (showTimestamps) {
        const [start, end] = getTimestampsFromMedia(video)
        presenceData.startTimestamp = start
        presenceData.endTimestamp = end
      }
      else {
        delete presenceData.startTimestamp
      }
    }

    if (showButtons) {
      const kind = isSeries ? 'series' : 'movie'
      presenceData.buttons = [{
        label: 'Regarder',
        url: contentUrl(kind, pageData('watch-id')) ?? href,
      }]
    }

    presence.setActivity(presenceData)
    return
  }

  const title = pageData('title')
  const cover = absoluteUrl(pageData('image'))
  let linkLabel: string | null = null
  let linkUrl = href

  switch (section) {
    case 'movie':
    case 'series': {
      const isSeries = section === 'series'
      presenceData.details = title ?? (isSeries ? 'Une série' : 'Un film')
      presenceData.state = join(
        isSeries ? 'Consulte la fiche de la série' : 'Consulte la fiche du film',
        pageData('subtitle'),
      )
      linkLabel = 'Regarder'
      linkUrl = contentUrl(section, pageData('id')) ?? href
      break
    }

    case 'actor':
      presenceData.details = title ?? 'Une personnalité'
      presenceData.state = join('Consulte la filmographie', pageData('subtitle'))
      linkLabel = 'Voir la fiche'
      linkUrl = contentUrl('actor', pageData('id')) ?? href
      break

    case 'franchise':
      presenceData.details = title ?? 'Une franchise'
      presenceData.state = join('Explore la franchise', pageData('subtitle'))
      linkLabel = 'Voir la franchise'
      linkUrl = contentUrl('franchise', pageData('id')) ?? href
      break

    case 'catalogue':
      presenceData.details = 'Catalogue'
      presenceData.state = join(pageData('subtitle'), pageData('genre')) || 'Explore le catalogue'
      break

    case 'top-10':
      presenceData.details = 'Top 10'
      presenceData.state = join('Les plus regardés', pageData('subtitle'))
      break

    case 'aleatoire':
      presenceData.details = title ? `Tirage : ${title}` : 'Roulette Nakios'
      presenceData.state = pageData('subtitle') ?? 'Se laisse choisir un titre'
      break

    case 'tv': {
      presenceData.details = 'TV en direct'
      presenceData.state = title ? join(title, pageData('subtitle')) : 'Parcourt les chaînes'
      if (title) {
        presenceData.smallImageKey = Assets.Live
        presenceData.smallImageText = 'En direct'
        linkLabel = 'Regarder la TV'
      }
      break
    }

    case 'suggestions':
      presenceData.details = 'Suggestions'
      presenceData.state = slug === 'create' ? 'Propose un titre à ajouter' : 'Parcourt les demandes'
      break

    case 'settings':
      presenceData.details = 'Paramètres'
      presenceData.state = SETTINGS_TABS[slug] ?? 'Règle son compte'
      break

    default: {
      const known = STATIC_PAGES[section]
      if (known) {
        presenceData.details = known.details
        presenceData.state = known.state
      }
      else {
        presenceData.details = 'Page introuvable'
        presenceData.state = 'S\'est perdu quelque part'
      }
    }
  }

  if (showCovers && cover)
    presenceData.largeImageKey = cover

  if (showButtons && linkLabel)
    presenceData.buttons = [{ label: linkLabel, url: linkUrl }]

  if (!showTimestamps)
    delete presenceData.startTimestamp

  presence.setActivity(presenceData)
})
