export enum LogoBlackBg {
  LogoPlaying = 'https://i.imgur.com/pLQzxWn.gif',
  LogoPaused = 'https://i.imgur.com/H5FGfEr.gif',
  LogoPlayingPink = 'https://i.imgur.com/i11ozrR.gif',
  LogoPausedPink = 'https://i.imgur.com/MJj43VN.gif',
  LogoPlayingLightPink = 'https://i.imgur.com/RhQEnCC.gif',
  LogoPausedLightPink = 'https://i.imgur.com/tKuXbE0.gif',
  LogoPlayingYellow = 'https://i.imgur.com/TGNtJYd.gif',
  LogoPausedYellow = 'https://i.imgur.com/DDx4v5n.gif',
  LogoPlayingLilac = 'https://i.imgur.com/VRJGxcE.gif',
  LogoPausedLilac = 'https://i.imgur.com/UNUXWpj.gif',
  LogoPlayingPurple = 'https://i.imgur.com/a0CWY5t.gif',
  LogoPausedPurple = 'https://i.imgur.com/i69Flpi.gif',
  LogoPlayingDarkPurple = 'https://i.imgur.com/eGlVMjg.gif',
  LogoPausedDarkPurple = 'https://i.imgur.com/M0RKXxf.gif',
  LogoPlayingRed = 'https://i.imgur.com/LTmPPQI.gif',
  LogoPausedRed = 'http://i.imgur.com/1EImOTT.gif',
  LogoPlayingOrange = 'https://i.imgur.com/NRB76Qq.gif',
  LogoPausedOrange = 'https://i.imgur.com/1w9TNQw.gif',
  LogoPlayingCyan = 'https://i.imgur.com/2g07TTF.gif',
  LogoPausedCyan = 'https://i.imgur.com/uQmGe17.gif',
  LogoPlayingGreen = 'https://i.imgur.com/18w2Tf1.gif',
  LogoPausedGreen = 'https://i.imgur.com/27hTfHw.gif',
  LogoPlayingGrey = 'https://i.imgur.com/kCvqOpp.gif',
  LogoPausedGrey = 'https://i.imgur.com/bAkj9Gg.gif',
  LogoPlayingWhite = 'http://i.imgur.com/K4iMdXi.gif',
  LogoPausedWhite = 'https://i.imgur.com/0zr9gjs.gif',
  LogoPlayingBlack = 'https://i.imgur.com/wb7td4d.gif',
  LogoPausedBlack = 'https://i.imgur.com/V8hlLgN.gif',
  LogoPlayingBeige = 'https://i.imgur.com/zfLF73V.gif',
  LogoPausedBeige = 'https://i.imgur.com/phtChNf.gif',

}

export enum LogoWhiteBg {
  LogoPlaying = 'https://i.imgur.com/SWgk97O.gif',
  LogoPaused = 'https://i.imgur.com/jIRiKAe.gif',
  LogoPlayingPink = 'https://i.imgur.com/LjdDYow.gif',
  LogoPausedPink = 'https://i.imgur.com/V4t4Em5.gif',
  LogoPlayingLightPink = 'https://i.imgur.com/fQQz6EN.gif',
  LogoPausedLightPink = 'https://i.imgur.com/99ZzLI3.gif',
  LogoPlayingYellow = 'https://i.imgur.com/pa6zapJ.gif',
  LogoPausedYellow = 'https://i.imgur.com/QYBEyrE.gif',
  LogoPlayingLilac = 'https://i.imgur.com/TmWL0Ea.gif',
  LogoPausedLilac = 'https://i.imgur.com/WY2daZ5.gif',
  LogoPlayingPurple = 'https://i.imgur.com/cluBqwh.gif',
  LogoPausedPurple = 'https://i.imgur.com/xf0Xc3S.gif',
  LogoPlayingDarkPurple = 'https://i.imgur.com/AK12cr1.gif',
  LogoPausedDarkPurple = 'https://i.imgur.com/xRKbwMY.gif',
  LogoPlayingRed = 'https://i.imgur.com/lhA5BXu.gif',
  LogoPausedRed = 'https://i.imgur.com/8IMG1lI.gif',
  LogoPlayingOrange = 'https://i.imgur.com/7tePS4g.gif',
  LogoPausedOrange = 'https://i.imgur.com/VLNKmY9.gif',
  LogoPlayingCyan = 'https://i.imgur.com/ig2EAYM.gif',
  LogoPausedCyan = 'https://i.imgur.com/ieYN7Zs.gif',
  LogoPlayingGreen = 'https://i.imgur.com/fBXgQ8r.gif',
  LogoPausedGreen = 'https://i.imgur.com/N2CBeFi.gif',
  LogoPlayingGrey = 'https://i.imgur.com/HU5nkZj.gif',
  LogoPausedGrey = 'https://i.imgur.com/kzQWnzn.gif',
  LogoPlayingWhite = 'http://i.imgur.com/K4iMdXi.gif',
  LogoPausedWhite = 'https://i.imgur.com/0zr9gjs.gif',
  LogoPlayingBlack = 'https://i.imgur.com/OVVD6Af.gif',
  LogoPausedBlack = 'https://i.imgur.com/Vgdo11d.gif',
  LogoPlayingBeige = 'https://i.imgur.com/hWvUfCp.gif',
  LogoPausedBeige = 'https://i.imgur.com/OQeqnmc.gif',
}

export enum LogoRemovedBg {
  LogoPlaying = 'https://i.imgur.com/yQdt0iC.gif',
  LogoPaused = 'https://i.imgur.com/8A54UVo.gif',
  LogoPlayingPink = 'https://i.imgur.com/UqxgWT7.gif',
  LogoPausedPink = 'https://i.imgur.com/b4BUJAY.gif',
  LogoPlayingLightPink = 'https://i.imgur.com/iEtzImn.gif',
  LogoPausedLightPink = 'https://i.imgur.com/rZ8YgkS.gif',
  LogoPlayingYellow = 'https://i.imgur.com/j0CAZRW.gif',
  LogoPausedYellow = 'https://i.imgur.com/oYHEtas.gif',
  LogoPlayingLilac = 'https://i.imgur.com/79ZLp7p.gif',
  LogoPausedLilac = 'http://i.imgur.com/GhCdmsK.gif',
  LogoPlayingPurple = 'https://i.imgur.com/Wc6Inob.gif',
  LogoPausedPurple = 'https://i.imgur.com/aVYMu7N.gif',
  LogoPlayingDarkPurple = 'https://i.imgur.com/5PpvlaI.gif',
  LogoPausedDarkPurple = 'https://i.imgur.com/BSSd03B.gif',
  LogoPlayingRed = 'https://i.imgur.com/oKTKzGo.gif',
  LogoPausedRed = 'https://i.imgur.com/lxXhcxJ.gif',
  LogoPlayingOrange = 'https://i.imgur.com/EWqgfzW.gif',
  LogoPausedOrange = 'https://i.imgur.com/h7iaVHo.gif',
  LogoPlayingCyan = 'https://i.imgur.com/BjGKt5R.gif',
  LogoPausedCyan = 'https://i.imgur.com/KdXkKNA.gif',
  LogoPlayingGreen = 'https://i.imgur.com/zc5CAy3.gif',
  LogoPausedGreen = 'https://i.imgur.com/eBXcng3.gif',
  LogoPlayingGrey = 'https://i.imgur.com/nOcgCL7.gif',
  LogoPausedGrey = 'https://i.imgur.com/rpf6BVM.gif',
  LogoPlayingWhite = 'https://i.imgur.com/dRRwuMG.gif',
  LogoPausedWhite = 'https://i.imgur.com/xlFh2Kh.gif',
  LogoPlayingBlack = 'https://i.imgur.com/NkDR6UG.gif',
  LogoPausedBlack = 'https://i.imgur.com/LzX7iNL.gif',
  LogoPlayingBeige = 'https://i.imgur.com/kojqjhQ.gif',
  LogoPausedBeige = 'https://i.imgur.com/Ls6MCWG.gif',

}
