export enum LogoBlackBg {
  LogoPlaying = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/0.gif',
  LogoPaused = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/1.gif',
  LogoPlayingPink = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/2.gif',
  LogoPausedPink = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/3.gif',
  LogoPlayingLightPink = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/4.gif',
  LogoPausedLightPink = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/5.gif',
  LogoPlayingYellow = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/6.gif',
  LogoPausedYellow = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/7.gif',
  LogoPlayingLilac = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/8.gif',
  LogoPausedLilac = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/9.gif',
  LogoPlayingPurple = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/10.gif',
  LogoPausedPurple = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/11.gif',
  LogoPlayingDarkPurple = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/12.gif',
  LogoPausedDarkPurple = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/13.gif',
  LogoPlayingRed = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/14.gif',
  LogoPausedRed = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/15.gif',
  LogoPlayingOrange = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/16.gif',
  LogoPausedOrange = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/17.gif',
  LogoPlayingCyan = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/18.gif',
  LogoPausedCyan = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/19.gif',
  LogoPlayingGreen = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/20.gif',
  LogoPausedGreen = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/21.gif',
  LogoPlayingGrey = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/22.gif',
  LogoPausedGrey = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/23.gif',
  LogoPlayingWhite = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/24.gif',
  LogoPausedWhite = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/25.gif',
  LogoPlayingBlack = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/26.gif',
  LogoPausedBlack = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/27.gif',
  LogoPlayingBeige = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/28.gif',
  LogoPausedBeige = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/29.gif',

}

export enum LogoWhiteBg {
  LogoPlaying = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/30.gif',
  LogoPaused = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/31.gif',
  LogoPlayingPink = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/32.gif',
  LogoPausedPink = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/33.gif',
  LogoPlayingLightPink = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/34.gif',
  LogoPausedLightPink = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/35.gif',
  LogoPlayingYellow = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/36.gif',
  LogoPausedYellow = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/37.gif',
  LogoPlayingLilac = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/38.gif',
  LogoPausedLilac = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/39.gif',
  LogoPlayingPurple = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/40.gif',
  LogoPausedPurple = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/41.gif',
  LogoPlayingDarkPurple = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/42.gif',
  LogoPausedDarkPurple = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/43.gif',
  LogoPlayingRed = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/44.gif',
  LogoPausedRed = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/45.gif',
  LogoPlayingOrange = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/46.gif',
  LogoPausedOrange = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/47.gif',
  LogoPlayingCyan = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/48.gif',
  LogoPausedCyan = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/49.gif',
  LogoPlayingGreen = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/50.gif',
  LogoPausedGreen = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/51.gif',
  LogoPlayingGrey = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/52.gif',
  LogoPausedGrey = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/53.gif',
  LogoPlayingWhite = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/24.gif',
  LogoPausedWhite = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/25.gif',
  LogoPlayingBlack = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/54.gif',
  LogoPausedBlack = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/55.gif',
  LogoPlayingBeige = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/56.gif',
  LogoPausedBeige = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/57.gif',
}

export enum LogoRemovedBg {
  LogoPlaying = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/58.gif',
  LogoPaused = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/59.gif',
  LogoPlayingPink = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/60.gif',
  LogoPausedPink = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/61.gif',
  LogoPlayingLightPink = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/62.gif',
  LogoPausedLightPink = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/63.gif',
  LogoPlayingYellow = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/64.gif',
  LogoPausedYellow = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/65.gif',
  LogoPlayingLilac = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/66.gif',
  LogoPausedLilac = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/67.gif',
  LogoPlayingPurple = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/68.gif',
  LogoPausedPurple = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/69.gif',
  LogoPlayingDarkPurple = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/70.gif',
  LogoPausedDarkPurple = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/71.gif',
  LogoPlayingRed = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/72.gif',
  LogoPausedRed = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/73.gif',
  LogoPlayingOrange = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/74.gif',
  LogoPausedOrange = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/75.gif',
  LogoPlayingCyan = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/76.gif',
  LogoPausedCyan = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/77.gif',
  LogoPlayingGreen = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/78.gif',
  LogoPausedGreen = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/79.gif',
  LogoPlayingGrey = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/80.gif',
  LogoPausedGrey = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/81.gif',
  LogoPlayingWhite = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/82.gif',
  LogoPausedWhite = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/83.gif',
  LogoPlayingBlack = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/84.gif',
  LogoPausedBlack = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/85.gif',
  LogoPlayingBeige = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/86.gif',
  LogoPausedBeige = 'https://cdn.rcd.gg/PreMiD/websites/R/Rythm/assets/87.gif',

}
